### ISSUE TITLE
LZ4 decompression unsupported

### ISSUE THREAD

**Issue by philmadden83** [Yelp/kafka-utils#133]
We're trying to use your utils to reset a consumer offset for a topic that is using LZ4 compression. When we run the command we get the following response.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kafka/future.py", line 79, in _call_backs
    f(value)
  File "/usr/local/lib/python2.7/dist-packages/kafka/consumer/fetcher.py", line 760, in _handle_fetch_response
    unpacked = list(self._unpack_message_set(tp, messages))
  File "/usr/local/lib/python2.7/dist-packages/kafka/consumer/fetcher.py", line 482, in _unpack_message_set
    inner_mset = msg.decompress()
  File "/usr/local/lib/python2.7/dist-packages/kafka/protocol/message.py", line 129, in decompress
    assert has_lz4(), 'LZ4 decompression unsupported'
AssertionError: LZ4 decompression unsupported
ERROR:kafka.future:Error processing callback
```

**Comment by philmadden83** [comment]
Closing due to issue being with the kafka library not your utils.
