### ISSUE TITLE
Not able to do a rolling bounce

### ISSUE THREAD

**Issue by jmarkan** [Yelp/kafka-utils#147]
Hey guys,
I recently set kafka-utils up and while I was able to run a bunch of commands to check ISR etc. However, I get a lot of errors when trying to run the rolling restart. Here is the output of the command: ./kafka-rolling-restart --cluster-type alpha-cluster

Will restart the following brokers in alpha-cluster:
  6001: 10.2.90.177
  6002: 10.2.68.139
  6003: 10.2.69.188
Do you want to restart these brokers? yes
Execute restart
Traceback (most recent call last):
  File "./kafka-rolling-restart", line 6, in <module>
    run()
  File "build/bdist.linux-x86_64/egg/kafka_utils/kafka_rolling_restart/main.py", line 501, in run
  File "build/bdist.linux-x86_64/egg/kafka_utils/kafka_rolling_restart/main.py", line 384, in execute_rolling_restart
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "build/bdist.linux-x86_64/egg/kafka_utils/util/ssh.py", line 145, in ssh
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 307, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 520, in _auth
    raise SSHException('No authentication methods available')
paramiko.ssh_exception.**SSHException: No authentication methods available**

Here are the contents of my alpha-cluster.yaml file:

clusters:
    alpha-cluster:
      broker_list:
        - "broker1-IP:9092,broker2-IP:9092,broker2-IP:9092"
      zookeeper: "ZK-ELB:80"
local_config:
    cluster: alpha-cluster

Is there any obvious config I'm missing?

**Comment by TheyDroppedMe** [comment]
Make sure the user you are executing the kafka-rolling-restart tool as has an ssh-key configured for passwordless ssh, and that the user exists on all the kafka nodes and has passwordless sudo.

**Comment by simplesteph** [comment]
or set up correctly your `~/.ssh/config`

**Comment by brettrann** [comment]
would be nice if it passed on the sudo password challenge instead of swallowing it though.

(we have a policy setup so don't need it)
