### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by roarman136** [Yelp/kafka-utils#158]
Support SSL connections using kafka-utils

**Comment by wadhwasam** [comment]
Does Kafka-utils support SSL as I am getting the following errors.  

Here is my listener in server.properties
listeners=SSL://<myFQDN>:9093

Traceback (most recent call last):
  File "/bin/kafka-consumer-manager", line 6, in <module>
    run()
  File "/usr/lib/python2.7/site-packages/kafka_utils/kafka_consumer_manager/main.py", line 90, in run
    args.command(args, conf)
  File "/usr/lib/python2.7/site-packages/kafka_utils/kafka_consumer_manager/commands/list_groups.py", line 86, in run
    kafka_groups = cls.get_kafka_groups(cluster_config)
  File "/usr/lib/python2.7/site-packages/kafka_utils/kafka_consumer_manager/commands/list_groups.py", line 60, in get_kafka_groups
    return list(kafka_group_reader.read_groups().keys())
  File "/usr/lib/python2.7/site-packages/kafka_utils/kafka_consumer_manager/util.py", line 189, in read_groups
    max_partition_fetch_bytes=10 * 1024 * 1024,  # 10MB
  File "/usr/lib/python2.7/site-packages/kafka/consumer/group.py", line 314, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/usr/lib/python2.7/site-packages/kafka/client_async.py", line 210, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/lib/python2.7/site-packages/kafka/client_async.py", line 808, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

**Comment by josephlim75** [comment]
I would like to know if there is any planning for kafka-utils to support SSL ?  This is a great tool but in order to be used in an enterprise environment, we require SSL support.

**Comment by rohanamin** [comment]
We are also exploring this tool and found it to be very useful but ran into SSL issues. Are there any future requirement for SSL support ?

**Comment by techguy0079** [comment]
we found the tool useful , however due to security requirements can't adopt this tool as it seems it is unable to connect to SSL enabled Kafka and zookeeper (kafka 2.5 + zk 3.5.7)

**Comment by oferzi23** [comment]
+1 i wonder if any of the 100+ forks implement this...
